---

- name: gitea | binary
  tags:
    - package
  get_url:
    url: "{{ gitea_url }}"
    checksum: "{{ gitea_checksum }}"
    dest: /usr/bin/gitea
    mode: "0755"

- name: gitea | nginx
  include_role:
    name: nginx
    tasks_from: site.yml
  with_items: gitea

- name: gitea | systemd unit
  tags:
    - service
    - systemd
  template:
    src: gitea.service.j2
    dest: /etc/systemd/system/gitea.service
  notify: daemon-reload gitea

- name: gitea | service
  tags:
    - service
  service:
    name: gitea
    state: started
    enabled: yes
