---

- name: gitea | binary
  tags:
  - package
  get_url:
    url: "{{ gitea_url }}"
    checksum: "{{ gitea_checksum }}"
    dest: /usr/bin/gitea
    mode: "0755"
  notify: restart gitea

- name: gitea | config
  tags:
  - config
  template:
    src: app.ini.j2
    dest: /etc/gitea/conf/app.ini
  notify: restart gitea

- name: gitea | nginx
  vars:
    site: gitea
  include_role:
    name: nginx
    tasks_from: site.yml

- name: gitea | systemd unit
  tags:
  - service
  - systemd
  template:
    src: gitea.service.j2
    dest: /etc/systemd/system/gitea.service
  notify: 
  - daemon-reload 
  - restart gitea

- name: gitea | service
  tags:
  - service
  service:
    name: gitea
    state: started
    enabled: yes
